default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: React_rails_development

test:
  <<: *default
  database: React_rails_test

production:
  <<: *default
  database: React_rails_production
  username: React_rails
  password: <%= ENV["REACT_RAILS_DATABASE_PASSWORD"] %>